Projekt_SZT/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from blog.views import index, show_profile, show_edit_userdata_page, edit_profile, \
    post_modify, post_detail, new_post, add_comment_to_post, comment_approve, comment_remove, blog_categories, \
    show_user_post, show_post_by_categories, post_remove, post_publish

urlpatterns = [

                  url(r'^admin/', admin.site.urls),
                  url(r'^$', index, name='index'),
                  url(r'^accounts/', include('registration.backends.default.urls')),
                  url('', include('social.apps.django_app.urls', namespace='social')),
                  url(r'^show_categories/$', blog_categories, name='blog_categories'),
                  url(r'^post_from_categories/(?P<pk>[0-9]+)/$', show_post_by_categories,
                      name='show_post_by_categories'),
                  url(r'^show_profile/$', show_profile, name='show_profile'),
                  url(r'^new_post_form/$', post_modify, name='post_modify'),
                  url(r'^editprofile/$', show_edit_userdata_page, name='show_edit_userdata_page'),
                  url(r'^apply_form_edit/$', edit_profile, name='edit_profile'),
                  url(r'^tinymce/', include('tinymce.urls')),
                  url(r'^post/(?P<pk>[0-9]+)/$', post_detail, name='post_detail'),
                  url(r'^post/(?P<pk>\d+)/user_post/$', show_user_post, name='show_user_post'),
                  url(r'^post/(?P<pk>[0-9]+)/edit/$', post_modify, name='post_modify'),
                  url(r'^post/new/$', new_post, name='new_post'),
                  url(r'^post/(?P<pk>\d+)/remove/$', post_remove, name='post_remove'),
                  url(r'^post/(?P<pk>\d+)/publish/$', post_publish, name='post_publish'),
                  url(r'^post/(?P<pk>\d+)/comment/$', add_comment_to_post, name='add_comment_to_post'),
                  url(r'^comment/(?P<pk>\d+)/approve/$', comment_approve, name='comment_approve'),
                  url(r'^comment/(?P<pk>\d+)/remove/$', comment_remove, name='comment_remove'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals

from django.db import models
import os
from tagging.fields import TagField
from django.utils import timezone
from django.contrib.auth.models import User
from tinymce import models as tinymce_models
from django.contrib.auth.models import User, models
User._meta.local_fields[4].__dict__['_unique'] = True

def get_image(instance, filename):
    return '/'.join(['content', instance.author.username, filename])


class Category(models.Model):
    title = models.CharField(max_length=250, help_text='Maksymalnie 100 znakow')
    description = models.TextField(help_text="Opis kategorii.")

    class Meta:
        ordering = ["title"]
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/kategorie/%s/" % self.slug


class Post(models.Model):
    STATUS_CHOICES = (
        (1, 'Live'),
        (2, 'Szkic'),
    )
    author = models.ForeignKey(User)
    title = models.CharField(max_length=250, help_text='Maksymalnie 250 znakow')
    excerpt = models.CharField(blank=True, max_length=500,
                               help_text='Krotkie podsumowanie. Opcjonalne')
    content = tinymce_models.HTMLField()
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)
    categories = models.ManyToManyField(Category, related_name="posts")
    tags = TagField()
    post_image = models.ImageField(upload_to=get_image)
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)

    def publish(self):
        self.published_date = timezone.now()
        self.status = 1
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.ForeignKey(User)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Category, Comment
from django.contrib.auth.models import User
from tinymce.widgets import TinyMCE


class UserForm(forms.ModelForm):
    first_name = forms.CharField(label='first_name')
    last_name = forms.CharField(label='last_name')

    class Meta:
        model = User
        fields = ['first_name', 'last_name']


class PostForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(queryset=Category.objects.all().exclude(id=1))
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    class Meta:
        model = Post
        fields = ['title', 'excerpt', 'content', 'tags', 'status', 'post_image', 'categories']


    js = ('/media/tinymce/jscripts/tiny_mce/tiny_mce.js',
            '',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import Post, Category, Comment
from .forms import UserForm, PostForm, CommentForm
from django.shortcuts import get_object_or_404, redirect
from .search import get_query


def index(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'base.html', {'posts': posts})


def show_profile(request):
    return render(request, 'user/show_user.html')


def show_edit_userdata_page(request):
    return render(request, 'user/edit_user.html')


def edit_profile(request):
    user = request.user
    form = UserForm(request.POST, initial={'first_name': user.first_name, 'last_name': user.last_name})
    if form.is_valid():
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.save()
        return HttpResponseRedirect('%s' % (reverse('show_profile')))

    context = {
        "form": form
    }
    return render(request, "user/show_user.html", context)

@login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/post_detail.html', {'post': post, 'form': form})

@login_required
def post_modify(request, pk):
    post = get_object_or_404(Post, id=pk)
    if post.author != request.user:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('index')

    else:
        form = PostForm(instance=post)
    print(form.errors)
    return render(request, 'blog/new_post.html', {'form': form})


@login_required
def new_post(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():  # All validation rules pass
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    print(form.errors)
    return render(request, 'blog/new_post.html', {'form': form})


def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/post_detail.html', {'pk': pk})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('post_detail', pk=post_pk)


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('index')

@login_required
def show_user_post(request, pk):
    live_posts = Post.objects.filter(author_id=pk, status=1).order_by('published_date')
    other_posts = Post.objects.filter(author_id=request.user.id, status=2).order_by('published_date')
    return render(request, 'blog/show_user_posts.html', {'live_posts': live_posts, 'other_posts': other_posts})


@login_required
def show_post_by_categories(request, pk):
    post_cat = Post.objects.filter(categories__id=pk)
    return render(request, 'base.html', {'posts': post_cat})


@login_required
def blog_categories(request):
    categories = Category.objects.all()
    return render(request, 'blog/blog_categories.html', {'categories':categories})


def search(request):
    query_string = ''
    found_entries = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        entry_query = get_query(query_string, ['title'])
        found_entries = Post.objects.filter(entry_query).order_by('-published_date')
    elif ('w' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        entry_query = get_query(query_string, ['tags'])
        found_entries = Post.objects.filter(entry_query).order_by('-published_date')
    return render(request, 'base.html', {'posts': found_entries})

templates/blog/blog_categories.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}

<div>
    {% for category in categories %}
        <div class="col-xs-6" style="width:50%;">
            <div class="thumbnail">
                <p><b>Tytuł</b></p>
                <p><a href="{% url 'show_post_by_categories' pk=category.id %}">{{ category.title }}</a></p>

                <p><b>Opis</b></p>
                <p>{{ category.description }}</p>
            </div>

        </div>
    {% endfor %}
</div>

{% endblock %}

templates/blog/new_post.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
    <div class="col-xs-6">
        <div class="panel panel-info">
            <div class="panel2">Stwórz post</div>
            <p class="panel-body">
                <form method="POST" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    <p>
                        <label for="id_title">Tytuł</label>
                        {{ form.title }}
                    </p>
                    <p>
                        <label for="id_excerpt">Streszczenie</label>
                        {{ form.excerpt }}
                    </p>
                    <p>
                        <label for="id_content">Treść</label>
                        {{ form.content }}
                    </p>
                    <p>
                        <label for="id_categories">Kategoria</label>
                        {{ form.categories }}
                    </p>
                    <p>
                        <label for="id_status">Status</label>
                        {{ form.status }}
                    </p>
                    <p >
                        <label for="id_tags">Tagi</label>
                        {{ form.tags }}
                    </p>
                    <p>
                        <label for="id_post_image">Obrazek:</label>
                        {{ form.post_image }}
                    </p>
                    {{ form.errors }}
                    <button type="submit" class="save btn btn-default">Send</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block body %}
    <div class="col-lg-6">
        <div class="entry-post">
            <div class="post-content">
                <div class="entry-thumbnail">
                    <a href="#"><img class="img-responsive" src="{{ post.post_image.url }}"
                                     alt="Image"></a>
                </div>
                <div class="time">
                    {% if post.published_date %}
                            {{ post.published_date }}
                    {% else %}
                        <a class="btn btn-default" href="{% url 'post_publish' pk=post.pk %}">Opublikuj</a>
                    {% endif %}
                </div>
            </div>
            <div class="entry-title">
                <a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a>
            </div>
            {% if user.is_authenticated %}
                <a class="btn btn-default" href="{% url 'post_modify' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                <a class="btn btn-default" href="{% url 'post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
            {% endif %}
            <p>Tagi: {{ post.tags }}</p>
            <p>{{ post.content|safe }}</p>
        </div>
        {#        <a class="btn btn-default" href="{% url 'add_comment_to_post' pk=post.pk %}">Add comment</a>#}
        {% if user.is_authenticated %}
            <form method="POST" action="{% url 'add_comment_to_post' pk=post.pk %}">
                {% csrf_token %}
                <div class="panel panel-info comment-form">
                    <div class="comment-form-head ">Dodaj komentarz</div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label for="id_text">Treść:</label>
                            <p>{{ form.text }}</p>
                        </div>
                        <button type="submit" class="save btn btn-default">Wyślij</button>
                    </div>

                </div>

            </form>
        {% endif %}
        {% if user.is_authenticated %}
            <div class="col-md-6">
                {% for comment in post.comments.all %}
                    {% if user.is_authenticated and comment.approved_comment %}
                        <div class="comment">
                            <div class="date">
                                {{ comment.created_date }}
                            </div>
                            {% if request.user.first_name and request.user.first_name %}
                                <strong>{{ comment.author.first_name }} {{ comment.author.last_name }}</strong>
                            {% else %}<strong>{{ comment.author.first_name }}</strong>{% endif %}
                            <p>{{ comment.text|linebreaks }}</p>
                        </div>
                    {% endif %}
                {% empty %}
                    <p>Brak komentarzy</p>
                {% endfor %}
            </div>
            {% if request.user == post.author %}
                <div class="col-md-6">
                    <h3>Zweryfikuj komentarze</h3>
                    {% for comment in post.comments.all %}
                        {% if user.is_authenticated and not comment.approved_comment %}
                            <div class="comment">
                                <div class="date">
                                    {{ comment.created_date }}
                                    <a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}"><span
                                            class="glyphicon glyphicon-remove"></span></a>
                                    <a class="btn btn-default" href="{% url 'comment_approve' pk=comment.pk %}"><span
                                            class="glyphicon glyphicon-ok"></span></a>
                                </div>
                                {% if request.user.first_name and request.user.first_name %}
                                    <strong>{{ comment.author.first_name }} {{ comment.author.last_name }}</strong>
                                {% else %}<strong>{{ comment.author.first_name }}</strong>{% endif %}
                                <p>{{ comment.text|linebreaks }}</p>
                            </div>
                        {% endif %}
                    {% empty %}
                        <p>Brak komentarzy</p>
                    {% endfor %}
                </div>
            {% endif %}


        {% else %}
            <div class="row">
                <div>
                    <div class="comment">
                        <p>Zaloguj się, by dodać komentarz.</p>
                    </div>
                </div>
                <div>
                    {% for comment in post.comments.all %}
                        {% if comment.approved_comment %}
                            <div class="comment">
                                <div class="date">
                                    {{ comment.created_date }}
                                </div>
                                {% if request.user.first_name and request.user.first_name %}
                                    <strong>{{ comment.author.first_name }} {{ comment.author.last_name }}</strong>
                                {% else %}<strong>{{ comment.author.first_name }}</strong>{% endif %}
                                <p>{{ comment.text|linebreaks }}</p>
                            </div>
                        {% endif %}
                    {% empty %}
                        <p>Brak komentarzy</p>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>

{% endblock %}

templates/blog/show_user_posts.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}

    <div>
        <h3>Twoje szkice</h3>
        {% if other_posts %}
            {% for post in other_posts %}
                <div class="col-sm-4">
                    <div class="entry-post">
                        <div class="post-content">
                            <div class="entry-thumbnail">
                                <img src="{{ post.post_image.url }}">
                            </div>
                            <div class="time">
                                {% if post.published_date %}
                                    {{ post.published_date }}
                                {% else %}
                                    <a class="btn btn-default" href="{% url 'post_publish' pk=post.pk %}">Opublikuj</a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="entry-title">
                            <a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a>
                        </div>
                        <p>{{ post.excerpt }}.</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}

            <p>Brak szkiców</p>

        {% endif %}
        <h3>Opublikowane posty</h3>
        {% if live_posts %}
            {% for post in live_posts %}
                <div class="col-sm-4">
                    <div class="entry-post">
                        <div class="post-content">
                            <div class="entry-thumbnail">
                                <img src="{{ post.post_image.url }}">
                            </div>
                            <div class="time">
                                <a href="#">{{ post.published_date }}</a>
                            </div>
                        </div>
                        <div class="entry-title">
                            <a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a>
                        </div>
                        <p>{{ post.excerpt }}.</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}

            <p>Brak szkiców</p>

        {% endif %}

    </div>

{% endblock %}